import type { Metadata } from "next";
import { Outfit, Instrument_Sans } from "next/font/google";
import localFont from 'next/font/local';
import "./globals.css";

export const clashDisplay = localFont({
  src: [
    { path: '../../public/fonts/ClashDisplay-Extralight.otf', weight: '200', style: 'normal' },
    { path: '../../public/fonts/ClashDisplay-Light.otf', weight: '300', style: 'normal' },
    { path: '../../public/fonts/ClashDisplay-Regular.otf', weight: '400', style: 'normal' },
    { path: '../../public/fonts/ClashDisplay-Medium.otf', weight: '500', style: 'normal' },
    { path: '../../public/fonts/ClashDisplay-Semibold.otf', weight: '600', style: 'normal' },
    { path: '../../public/fonts/ClashDisplay-Bold.otf', weight: '700', style: 'normal' },
  ],
  variable: '--font-clash',
});

const outfitSans = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});

const instrumentSans = Instrument_Sans({
  variable: "--font-instrument-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${outfitSans.variable} ${clashDisplay.variable} ${instrumentSans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
